build:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - "*.mk"
        - ".python-version"
        - "infrastructure/**/*"
        - "Makefile"
        - "pyproject.toml"
        - "uv.lock"
    - head-branch:
      - '^build'

chore:
  - head-branch:
    - '^chore'

ci:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - ".github/**/*"
    - head-branch:
      - '^ci'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - ".python-version"
      - "uv.lock"

docs:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - "CHANGELOG*"
        - "docs/**/*"
        - "README*"
    - head-branch:
      - '^docs'

feat:
  - head-branch:
    - '^feat'

fix:
  - head-branch:
    - '^fix'

refactor:
  - head-branch:
    - '^refactor'

style:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - ".editorconfig"
        - ".flake8"
        - ".pre-commit-config.yaml"
    - head-branch:
      - '^style'

test:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - ".env.test"
        - "tests/**/*"
    - head-branch:
      - '^test'
