default_language_version:
  python: &python_version "python3.10"
exclude: ^(archive|assets|migrations)/.*|.*/(migrations|test-data|vendor)/.*|.*\.svg$
minimum_pre_commit_version: "1.17.0"
repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v4.18.0"
    hooks:
      - id: "commitizen"
        # By default commitizen using `python3` language version, so
        # needed to provide concrete version here as well
        language_version: *python_version
        stages: ["commit-msg"]

  - repo: "https://github.com/astral-sh/uv-pre-commit"
    rev: "0.12.5"
    hooks:
      - id: "uv-lock"
        name: "Check uv.lock"

  - repo: "https://github.com/tox-dev/pyproject-fmt"
    rev: "v2.28.0"
    hooks:
      - id: "pyproject-fmt"
        name: "Format pyproject.toml"
        additional_dependencies:
          - "tomli==2.4.1"

  - repo: "https://github.com/Kludex/no-optional"
    rev: "0.4.0"
    hooks:
      - id: "no_optional"
        name: "Format code (no-optional)"

  - repo: "https://github.com/PyCQA/isort"
    rev: "8.0.1"
    hooks:
      - id: "isort"
        name: "Format code (isort)"
        exclude: ^docs/.*$

  - repo: "https://github.com/psf/black-pre-commit-mirror"
    rev: "26.5.1"
    hooks:
      - id: "black"
        name: "Format code (black)"
        exclude: ^docs/.*$
        language_version: *python_version

  - repo: "https://github.com/asottile/blacken-docs"
    rev: "1.20.0"
    hooks:
      - id: "blacken-docs"
        name: "Format docs (blacken-docs)"
        args: ["-l", "64"]
        additional_dependencies:
          - "black==26.5.1"

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"

  - repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: "v1.10.0"
    hooks:
      - id: "python-check-blanket-noqa"
      - id: "python-check-blanket-type-ignore"
      - id: "rst-backticks"
      - id: "rst-directive-colons"
      - id: "rst-inline-touching-normal"

  - repo: "https://github.com/PyCQA/flake8"
    rev: "7.3.0"
    hooks:
      - id: "flake8"
        name: "Lint code (flake8)"
        additional_dependencies: &flake8_additional_dependencies
          - "flake8-bugbear==25.11.29"
          - "flake8-builtins==3.1.0"
          - "flake8-comprehensions==3.17.0"
          - "flake8-implicit-str-concat==0.7.0"
          - "flake8-isort==7.0.0"
          - "flake8-logging==1.8.0"
          - "flake8-mutable==1.2.0"
          - "flake8-pep585==0.1.7"
          - "flake8-quotes==3.4.0"
          - "flake8-tidy-imports==4.12.0"
          - "flake8-type-checking==3.2.0"
          - "flake8-variables-names==0.0.6"
          - "flake8==7.3.0"
          - "pep8-naming==0.15.1"
        exclude: ^docs/.*$

  - repo: "https://github.com/asottile/yesqa"
    rev: "v1.5.0"
    hooks:
      - id: "yesqa"
        name: "Lint code (yesqa)"
        additional_dependencies: *flake8_additional_dependencies
        exclude: ^docs/.*$

  - repo: "local"
    hooks:
      - id: "mypy"
        name: "Lint code (mypy)"
        entry: ".venv/bin/mypy"
        language: "python"
        "types": ["python"]
        require_serial: true
        exclude: ^(.*/)?(docs|migrations|tests)/.*$

  - repo: "https://github.com/shellcheck-py/shellcheck-py"
    rev: "v0.11.0.1"
    hooks:
      - id: "shellcheck"
        name: "Lint scripts (shellcheck)"

  - repo: "https://github.com/Mateusz-Grzelinski/actionlint-py"
    rev: "v1.7.12.24"
    hooks:
      - id: "actionlint"
        name: "Lint workflows (actionlint)"
        additional_dependencies:
          - "shellcheck-py==0.11.0.1"

  - repo: "https://github.com/zizmorcore/zizmor-pre-commit"
    rev: "v1.29.0"
    hooks:
      - id: "zizmor"
        name: "Lint workflows (zizmor)"
        args: ["--no-progress", "--fix"]
