version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      - "curl -sSL https://install.python-poetry.org | python3 -"
      # Tell poetry to not create virtual environments
      - "${HOME}/.local/bin/poetry config virtualenvs.create false"
      - "${HOME}/.local/bin/poetry config --local virtualenvs.create false"
    post_install:
      # Show current working directory
      - "pwd"
      # Install project and docs dependencies
      - "${HOME}/.local/bin/poetry install --only main,docs"

sphinx:
  configuration: "./docs/conf.py"
