#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# aiohttp-middlewares documentation build configuration file, created by
# sphinx-quickstart on Sun May 14 20:32:17 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import datetime
import re
import sys
from pathlib import Path


ROOT_PATH = Path(__file__).parent.parent
SRC_PATH = ROOT_PATH / "src"
sys.path.insert(0, str(SRC_PATH))

INIT_PY = (SRC_PATH / "aiohttp_middlewares" / "__init__.py").read_text()
VERSION = re.findall('__version__ = "([^"]+)"', INIT_PY)[0]
TODAY = datetime.date.today()


extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
    "sphinxext.opengraph",
]

templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"

project = "aiohttp-middlewares"
description = "Collection of useful middlewares for aiohttp applications."
copyright = f"2017-{TODAY.year}, Igor Davydenko"
author = "Igor Davydenko"

version = ".".join(VERSION.split(".")[:2])
release = VERSION

language = "en"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
pygments_style = "sphinx"
pygments_dark_style = "monokai"

html_theme = "furo"
html_theme_options = {}
html_static_path = ["_static"]

htmlhelp_basename = "aiohttp-middlewaresdoc"
latex_elements = {}
latex_documents = [
    (
        master_doc,
        "aiohttp-middlewares.tex",
        "aiohttp-middlewares Documentation",
        "Igor Davydenko",
        "manual",
    )
]

man_pages = [
    (
        master_doc,
        "aiohttp-middlewares",
        "aiohttp-middlewares Documentation",
        [author],
        1,
    )
]

texinfo_documents = [
    (
        master_doc,
        "aiohttp-middlewares",
        "aiohttp-middlewares Documentation",
        author,
        "aiohttp-middlewares",
        description,
        "Miscellaneous",
    )
]

intersphinx_mapping = {
    "https://docs.python.org/3/": None,
    "https://aiohttp.readthedocs.io/en/stable/": None,
}

ogp_site_url = "https://aiohttp-middlewares.readthedocs.io"
ogp_site_name = project
ogp_image = "https://repository-images.githubusercontent.com/91174188/e1a75000-4063-11ea-8c47-f34e26fe6d40"
