defaults:
  run:
    shell: "bash"

name: "CI"

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  PYTHONUNBUFFERED: "1"
  # Get latest versions by running,
  #
  # ```bash
  # pip-latest-release badabump poetry tox tox-gh-actions twine
  # ```
  #
  BADABUMP_VERSION: "21.3.3"
  POETRY_VERSION: "1.1.13"
  TOX_VERSION: "3.25.0"
  TOX_GH_ACTIONS_VERSION: "2.9.1"
  TWINE_VERSION: "4.0.1"

jobs:
  install:
    name: "Install & cache package"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install poetry"
        uses: "snok/install-poetry@v1.3.1"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Cache venv"
        uses: "actions/cache@v3.0.4"
        with:
          path: "./.venv/"
          key: "venv-${{ matrix.os }}-dev-${{ hashFiles('poetry.lock') }}"

      - name: "Install package"
        run: "poetry install"

  dev:
    needs: ["install"]
    name: "Verify package is installed well"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Cache venv"
        uses: "actions/cache@v3.0.4"
        with:
          path: "./.venv/"
          key: "venv-${{ runner.os }}-dev-${{ hashFiles('poetry.lock') }}"

      - name: "Install package"
        run: "poetry install"

      - name: "Import package"
        run: "poetry run python3 -c 'import aiohttp_middlewares'"

  docs:
    name: "Verify documentation build well"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install docs requirements"
        run: "python3 -m pip install -r ./docs/requirements.txt -r ./docs/requirements-sphinx.txt"

      - name: "Build docs"
        run: "python3 -m sphinx -b html ./docs/ ./docs/_build/"

  test:
    needs: ["install"]
    name: "Python ${{ matrix.python-version }}"

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-beta.3"]
        include:
          - python-version: "3.7"
            python-cache-key: "3.7"

          - python-version: "3.8"
            python-cache-key: "3.8"

          - python-version: "3.9"
            python-cache-key: "3.9"

          - python-version: "3.10"
            python-cache-key: "dev"

          - python-version: "3.11.0-beta.3"
            python-cache-key: "3.11.0-beta.3"

    runs-on: "ubuntu-latest"
    continue-on-error: "${{ startsWith(matrix.python-version, '3.11') }}"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install poetry"
        uses: "snok/install-poetry@v1.3.1"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Install other deps"
        run: "python3 -m pip install tox==${{ env.TOX_VERSION }} tox-gh-actions==${{ env.TOX_GH_ACTIONS_VERSION }}"

      - name: "Cache venv"
        uses: "actions/cache@v3.0.4"
        with:
          path: "./.venv/"
          key: "venv-${{ runner.os }}-${{ matrix.python-cache-key }}-${{ hashFiles('poetry.lock') }}"

      - name: "Install package with dev dependencies"
        if: "${{ matrix.python-cache-key == 'dev' }}"
        run: "poetry install"

      - name: "Install package without dev dependencies"
        if: "${{ matrix.python-cache-key != 'dev' }}"
        run: "poetry install --no-dev"

      - name: "Run pre-commit"
        if: "${{ matrix.python-cache-key == 'dev' }}"
        uses: "pre-commit/action@v3.0.0"

      - name: "Run tests"
        run: "python3 -m tox"

      - name: "Send report to coveralls"
        if: "${{ matrix.python-cache-key == 'dev' }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "poetry run python3 -m coveralls --service=github"

  package:
    needs: ["test"]
    name: "Build & deploy package"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install poetry"
        uses: "snok/install-poetry@v1.3.1"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Build package"
        run: "poetry build"

      - name: "Check package"
        run: |
          set -euo pipefail

          python3 -m pip install twine==${{ env.TWINE_VERSION }}
          python3 -m twine check ./dist/*

      - name: "Publish package"
        if: "${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}"
        uses: "pypa/gh-action-pypi-publish@v1.5.0"
        with:
          user: "${{ secrets.PYPI_USERNAME }}"
          password: "${{ secrets.PYPI_PASSWORD }}"

  release:
    needs: ["package"]
    if: "${{ startsWith(github.ref, 'refs/tags/') }}"
    name: "Create GitHub release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Fetch git data"
        run: |
          set -euo pipefail

          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install badabump"
        run: "python3 -m pip install badabump==${{ env.BADABUMP_VERSION }}"

      - id: "badabump"
        name: "Run badabump"
        run: 'python3 -m badabump.ci prepare_release "${{ github.ref }}"'

      - name: "Create new release"
        uses: "actions/create-release@v1.1.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.badabump.outputs.tag_name }}"
          release_name: "${{ steps.badabump.outputs.release_name }}"
          body: "${{ steps.badabump.outputs.release_body }}"
          prerelease: "${{ steps.badabump.outputs.is_pre_release }}"
