defaults:
  run:
    shell: "bash"

name: "[REUSABLE] Build & Deploy Package"

on:
  workflow_call:
    inputs:
      twine-version:
        description: "Twine version to use."
        type: "string"
        required: false
        default: "7.0.0"

jobs:
  package:
    name: "Build & Deploy Package"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v7.0.1"
        with:
          persist-credentials: false

      - uses: "./.github/actions/setup_uv"

      - name: "Build package"
        run: "uv build"

      - name: "Check package"
        env:
          TWINE_VERSION: "${{ inputs.twine-version }}"
        run: 'uvx -p "$(cat ".python-version")" twine=="${TWINE_VERSION}" check dist/*'

      - name: "Publish package"
        if: "${{ startsWith(github.ref, 'refs/tags/') }}"
        uses: "pypa/gh-action-pypi-publish@v1.14.2"
        with:
          attestations: false  # Disable attestations until publishing to PyPI from reusable workflow will be fixed
