defaults:
  run:
    shell: "bash"

name: "[REUSABLE] Create GitHub Release"

on:
  workflow_call:
    secrets:
      release-token:
        description: "Token to use for creating release."
        required: true

jobs:
  release:
    name: "Create GitHub Release"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v7.0.1"
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - id: "badabump-cli"
        uses: "./.github/actions/setup_badabump/"

      - id: "badabump"
        name: "Run badabump"
        env:
          BADABUMP_CI: "${{ steps.badabump-cli.outputs.badabump-ci }}"
        run: '${BADABUMP_CI} prepare_release "${GITHUB_REF}"'

      - name: "Create new release"
        env:
          GH_TOKEN: "${{ secrets.release-token }}"
          IS_PRE_RELEASE: "${{ steps.badabump.outputs.is_pre_release }}"
          RELEASE_BODY: "${{ steps.badabump.outputs.release_body }}"
          RELEASE_NAME: "${{ steps.badabump.outputs.release_name }}"
          TAG_NAME: "${{ steps.badabump.outputs.tag_name }}"
        run: |
          set -euo pipefail

          args=()
          if [ "${IS_PRE_RELEASE}" = "true" ]; then
            args+=(--prerelease)
          fi

          gh release create "${TAG_NAME}" \
            --title "${RELEASE_NAME}" \
            --notes "${RELEASE_BODY}" \
            "${args[@]}"
