name: "Create GitHub Release"

on:
  workflow_call:
    inputs:
      badabump-version:
        description: "Badabump version to use."
        type: "string"
        required: false
        default: "21.3.3"

    secrets:
      GITHUB_TOKEN:
        description: "GitHub token to use."
        required: true

jobs:
  release:
    name: "Create GitHub Release"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - name: "Fetch git data"
        run: |
          set -euo pipefail

          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow

      - id: "python"
        name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install badabump"
        run: "pipx install --python='${{ steps.python.outputs.python-path }}' badabump==${{ inputs.badabump-version }}"

      - id: "badabump"
        name: "Run badabump"
        run: 'badabump-ci prepare_release "${{ github.ref }}"'

      - name: "Create new release"
        uses: "actions/create-release@v1.1.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.badabump.outputs.tag_name }}"
          release_name: "${{ steps.badabump.outputs.release_name }}"
          body: "${{ steps.badabump.outputs.release_body }}"
          prerelease: "${{ steps.badabump.outputs.is_pre_release }}"
