defaults:
  run:
    shell: "bash"

name: "[REUSABLE] Verify Docs Build Well"

on:
  workflow_call:

env:
  UV_FROZEN: "true"
  UV_NO_DEFAULT_GROUPS: "true"

jobs:
  build_docs:
    name: "Verify Docs Build Well"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v7.0.1"
        with:
          persist-credentials: false

      - id: "uv"
        uses: "./.github/actions/setup_uv/"

      - name: "Install docs dependencies"
        run: "uv sync --group=docs"

      - name: "Build docs"
        run: "uv run --group=docs -m sphinx -b html docs/ docs/_build/"
