defaults:
  run:
    shell: "bash"
permissions:
  contents: "read"
  pull-requests: "write"

name: "[AUTO] Pull Request Labeler"

on:
  - "pull_request_target"

jobs:
  labeler:
    name: "Pull Request Labeler"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/labeler@v7.0.0"
