defaults:
  run:
    shell: "bash"
permissions:
  contents: "read"

name: "[MANUAL] Create Release PR"

on:
  workflow_dispatch:
    inputs:
      args:
        description: "Badabump arguments (pass `--pre` to start or keep pre-release cycle)"
        required: false
        default: ""

env:
  PYTHONUNBUFFERED: "1"

jobs:
  create_release_pr:
    if: "${{ github.actor == 'playpauseandstop' }}"
    name: "Create Release PR"

    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v7.0.1"
        with:
          ref: "${{ github.event.repository.default_branch }}"
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - id: "badabump-cli"
        uses: "./.github/actions/setup_badabump/"

      - id: "badabump"
        name: "Run badabump"
        env:
          BADABUMP: "${{ steps.badabump-cli.outputs.badabump }}"
          BADABUMP_ARGS: "${{ github.event.inputs.args }}"
        run: |
          # shellcheck disable=SC2086
          ${BADABUMP} --ci ${BADABUMP_ARGS}

      - id: "token"
        uses: "actions/create-github-app-token@v3.2.0"
        with:
          app-id: "${{ secrets.BADABUMP_APP_ID }}"
          private-key: "${{ secrets.BADABUMP_APP_PRIVATE_KEY }}"
          permission-contents: "write"
          permission-pull-requests: "write"

      - name: "Create pull request with changed files"
        uses: "peter-evans/create-pull-request@v8.1.1"
        with:
          token: "${{ steps.token.outputs.token }}"
          commit-message: |
            ${{ steps.badabump.outputs.pr_title }}

            ${{ steps.badabump.outputs.changelog }}
          branch: "${{ steps.badabump.outputs.pr_branch }}"
          delete-branch: true
          title: "${{ steps.badabump.outputs.pr_title }}"
          body: "${{ steps.badabump.outputs.changelog }}"
          labels: "chore"
          reviewers: "playpauseandstop"
          assignees: "playpauseandstop"
