defaults:
  run:
    shell: "bash"

name: "Auto Create Release Tag"

on:
  pull_request:
    types: ["closed"]

env:
  PYTHONUNBUFFERED: "1"
  BADABUMP_VERSION: "21.3.3"

jobs:
  create_release_tag:
    if: "${{ startsWith(github.head_ref, 'chore/release-') && github.event.pull_request.merged == true }}"
    name: "Create release tag"

    runs-on: "ubuntu-latest"

    steps:
      - id: "token"
        uses: "tibdex/github-app-token@v1.5"
        with:
          app_id: "${{ secrets.BADABUMP_APP_ID }}"
          private_key: "${{ secrets.BADABUMP_APP_PRIVATE_KEY }}"

      - uses: "actions/checkout@v3.0.2"
        with:
          ref: "main"
          token: "${{ steps.token.outputs.token }}"

      - name: "Install Python"
        uses: "actions/setup-python@v4.0.0"
        with:
          python-version-file: ".python-version"

      - name: "Install badabump"
        run: "pipx install badabump==${{ env.BADABUMP_VERSION }}"

      - id: "badabump"
        name: "Run badabump"
        run: "badabump-ci prepare_tag"

      - name: "Create release tag from latest commit"
        run: |
          set -euo pipefail

          git config user.name badabump-release-bot[bot]
          git config user.email badabump-release-bot[bot]@users.noreply.github.com

          cat > ./tag_message.txt <<EOF
          ${{ steps.badabump.outputs.tag_message }}
          EOF

          git tag -a ${{ steps.badabump.outputs.tag_name }} -F ./tag_message.txt
          git push --tag
